---
- name: Load dash from archive
  docker_image:
    name: kubernetes-dashboard-amd64
    load_path: /home/fedora/install/dash.tar.gz
    pull: no
    state: present

- name: Load pos from archive
  docker_image:
    name: pause
    load_path: /home/fedora/install/pause.tar.gz
    pull: no
    state: present

- name: Load skydns from archive
  docker_image:
    name: skydns
    load_path: /home/fedora/install/skydns.tar.gz
    pull: no
    state: present

- name: Load kube2sky from archive
  docker_image:
    name: kube2sky
    load_path: /home/fedora/install/kube2sky.tar.gz
    pull: no
    state: present

- name: Load exechealth from archive
  docker_image:
    name: exechealth
    load_path: /home/fedora/install/health.tar.gz
    pull: no
    state: present

- name: Load etcd from archive
  docker_image:
    name: etcd
    load_path: /home/fedora/install/etcd.tar.gz
    pull: no
    state: present
