---
- name: Load dashboard from archive
  docker_image:
    name: kubernetes-dashboard-amd64
    load_path: /home/fedora/install/dashboard.tar.gz
    pull: no
    state: present

- name: Load pos from archive
  docker_image:
    name: pause
    load_path: /home/fedora/install/pause.tar.gz
    pull: no
    state: present

- name: Load kubedns-amd64 from archive
  docker_image:
    name: kubedns
    load_path: /home/fedora/install/kubedns.tar.gz
    pull: no
    state: present

- name: Load kube-dnsmasq from archive
  docker_image:
    name: kube-dnsmasq
    load_path: /home/fedora/install/kube-dnsmasq.tar.gz
    pull: no
    state: present

- name: Load exechealthz from archive
  docker_image:
    name: exechealthz
    load_path: /home/fedora/install/exechealthz.tar.gz
    pull: no
    state: present
