---
- name: Set the is_coreos fact
  set_fact:
    is_coreos: false

- name: Create the directory used to store binaries
  file: path={{ bin_dir }} state=directory

- name: Create Ansible temp directory
  file: path={{ ansible_temp_dir }} state=directory

# enable cpu and memory accounting for systemd services by default
- name: Create systemd dropin directory
  file: path=/etc/systemd/system/system.conf.d state=directory mode=0755
  when: source_type == "localBuild"

- name: Enable cpu and memory accounting for systemd services
  copy: src=kubernetes-accounting.conf dest="/etc/systemd/system/system.conf.d/kubernetes-accounting.conf"
  when: source_type == "localBuild"
  notify:
    - reload systemd
