---
- name: Force etcd_source_type to package manager 
  set_fact:
    etcd_source_type: "package-manager"
  when: not is_atomic and ansible_distribution != "Ubuntu" and not is_coreos

- name: Set the etcd_modified fact to true 
  set_fact:
    etcd_modified: true
  when: etcd_source_type == "package-manager" 
