apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cherrypick
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cherrypick
    spec:
      containers:
      - name: cherrypick
        command:
        - /mungegithub
        - --token-file=/etc/secret-volume/token
        - --organization=kubernetes
        - --project=kubernetes
        - --pr-mungers=cherrypick-must-have-milestone,cherrypick-clear-after-merge,cherrypick-queue
        - --state=all
        - --labels=cherrypick-candidate
        - --http-cache-dir=/cache/httpcache
        - --dry-run=true
        - --admin-port=9999
        - --repo-dir=/gitrepo
        - --period=3m
        image: docker.io/eparis/cherrypick:2016-03-14-7fb1dae
        ports:
        - name: status
          containerPort: 8080
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 600m
        volumeMounts:
        - mountPath: /etc/secret-volume
          name: cherrypick-secret-volume
        - mountPath: /gitrepo
          name: repo
      volumes:
      - name: cherrypick-secret-volume
        secret:
          secretName: cherrypick-secret-volume
      - name: repo
        emptyDir: {}
