---
- name: Set variables
  set_fact:
    build_dir: "/tmp/.ansible/build/{{ kmod_build_tag }}"
    install_dir: "/tmp/.ansible/install/{{ kmod_build_tag }}"
    artifact_tar: "/tmp/.ansible/opencontrail-vrouter-{{ kmod_build_tag }}.tgz"

- name: Create install tree
  file:
    path: "{{ install_dir }}/usr/bin"
    state: directory

- name: Create install tree (kmod)
  file:
    path: "{{ install_dir }}/lib/modules/{{ ansible_kernel }}/kernel/drivers/net"
    state: directory

- name: Install kmod
  command: install kbuild/vrouter.ko "{{ install_dir }}/lib/modules/{{ ansible_kernel }}/kernel/drivers/net"
  args:
    chdir: "{{ build_dir }}"
    creates: "{{ install_dir }}/lib/modules/{{ ansible_kernel }}/kernel/drivers/net/vrouter.ko"

- name: Create tarball
  command: tar zcf "{{ artifact_tar }}" .
  args:
    chdir: "{{ install_dir }}"
    creates: "{{ artifact_tar }}"

- name: Fetch tarball
  fetch: src="{{ artifact_tar }}" dest="/tmp/.ansible/artifacts/" flat=yes
