---
# Install Flannel.

- set_fact: 
    flannel_use_upstart: false

- set_fact:
    flannel_use_upstart: true
  when:  "{{ ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int < 15 }}"

- name: Set Flannel config file directory
  set_fact:
    flannel_config_dir: "/etc/sysconfig"

- name: Override Flannel config file directory for Ubuntu
  set_fact:
    flannel_config_dir: "/etc/flannel"
  when: flannel_use_upstart

- name: Create config file directory
  file: path={{ flannel_config_dir }} state=directory

- name: Install Flannel config file
  template: src=flanneld.j2 dest={{ flannel_config_dir }}/flanneld
  notify:
    - restart flannel
