---
- name: Prepare and write Flannel configuration to etcd
  include: config.yml

- name: Install Flannel
  include: client.yml
  when: inventory_hostname in groups['masters'] + groups['nodes']

- name: Enable flannel
  service: name=flanneld enabled=yes

- name: Start flannel
  service: name=flanneld state=started
  register: flannel_started
  notify:
    - restart docker
