---
# This playbook deploys a kubernetes cluster
# with the default addons.

- hosts: all
  gather_facts: false
  become: yes
  roles:
    - pre-ansible
  tags:
    - pre-ansible

# Install etcd
- include: deploy-etcd.yml

# Install docker
- hosts: all
  become: yes
  roles:
    - common
    - docker
  tags:
    - docker

# install flannel
- hosts:
    - masters
    - nodes
  become: yes
  roles:
    - { role: flannel, when: networking == 'flannel' }
  tags:
    - network-service-install

# install kube master services
- hosts: masters
  become: yes
  roles:
    - master
  tags:
    - masters

# launch addons, like dns
- hosts: masters
  become: yes
  roles:
    - kubernetes-addons
  tags:
    - addons
    - dns

# install kubernetes on the nodes
- hosts: nodes
  become: yes
  roles:
    - node
  tags:
    - nodes
