---
- wait_for:
   port: 22
   delay: 40
   timeout: 300

- name: get hostname facts
  raw: "hostname"
  register: hostname

- name: add hostname to /etc/hosts
  lineinfile:
    dest=/etc/hosts
    line='127.0.0.1 {{ hostname.stdout_lines[0] }}'
    regexp='^127\.0\.0\.1'
    state=present

- name: Get os_version from /etc/os-release
  raw: "echo 24"
  register: os_version
  always_run: yes

- name: Get distro name from /etc/os-release
  raw: "echo Fedora"
  register: distro
  always_run: yes

- name: Init the is_coreos fact
  set_fact:
    is_coreos: false

- name: Determine if Atomic
  raw: "test -f /run/ostree-booted"
  register: s
  changed_when: false
  failed_when: false
  always_run: yes

- name: Set the is_atomic fact
  set_fact:
    is_atomic: true
  when: s.rc == 0
