---
- name: Copy systemd tmpfile for apiserver
  copy:
    src: ../init/systemd/tmpfiles.d/
    dest: /etc/tmpfiles.d/
    mode: 0644
  notify: reload systemd

- name: Create the /var/lib/kubelet working directory
  file:
    path: /var/lib/kubelet
    state: directory
