---
- name: Init the did_install fact
  set_fact:
    did_install: false

- name: Set fact for Atomic Host package install
  set_fact:
    did_install: true
  when: is_atomic

- name: Set fact saying we did Fedora package install
  set_fact:
    did_install: true
  when: ansible_distribution == "Fedora" and ansible_distribution_release != "Rawhide"
