---
- name: Add {{ansible_env.USER}} to docker group
  become: yes
  user: >
    name='{{ansible_env.USER}}'
    state=present
    groups=docker,{{ansible_env.USER}}
    shell=/bin/bash
    append=yes
  tags: install-docker
