---
- name: Create config file directory
  file: path={{ docker_config_dir }} state=directory

- include: fedora-install.yml
  when: ansible_distribution == "Fedora"

#
# systemd service configuration uses EnvironmentFile (docker and docker-network)
# upstart service configuration sources docker_config_dir / docker
#
- name: Local vars for systemd installs
  set_fact:
    docker_config_net: "{{ docker_config_dir }}/docker-network"
    docker_env_export: ""

- name: Enable Docker
  service: name=docker enabled=yes
  notify:
    - start docker
